export const data = [
  {
    id: 1,
    title: "lightsound/nexst-tailwind",
    content: "Next.js starter template.",
    javascript: "24.5%",
    other: "10%",
    thumbnail: "/assets/img/Thumbnail.webp",
    typescript: "65.5%",
  },
  {
    id: 2,
    title: "lightsound/nexst-tailwind 1",
    content: "Next.js starter template.",
    javascript: "24.5%",
    other: "10%",
    thumbnail: "/assets/img/Thumbnail.webp",
    typescript: "65.5%",
  },
  {
    id: 3,
    title: "lightsound/nexst-tailwind 2",
    content: "Next.js starter template.",
    javascript: "24.5%",
    other: "10%",
    thumbnail: "/assets/img/Thumbnail.webp",
    typescript: "65.5%",
  },
  {
    id: 4,
    title: "lightsound/nexst-tailwind 3",
    content: "Next.js starter template.",
    javascript: "24.5%",
    other: "10%",
    thumbnail: "/assets/img/Thumbnail.webp",
    typescript: "65.5%",
  },
  {
    id: 5,
    title: "lightsound/nexst-tailwind 4",
    content: "Next.js starter template.",
    javascript: "24.5%",
    other: "10%",
    thumbnail: "/assets/img/Thumbnail.webp",
    typescript: "65.5%",
  },
  {
    id: 6,
    title: "lightsound/nexst-tailwind 5",
    content: "Next.js starter template.",
    javascript: "24.5%",
    other: "10%",
    thumbnail: "/assets/img/Thumbnail.webp",
    typescript: "65.5%",
  },
];
