export const data = [
  {
    id: 1,
    thumbnail: "/assets/img/Thumbnail.webp",
    title: "lightsound/nexst-tailwind",
    content: "Next.js starter template.",
    typescript: "65.5%",
    javascript: "33.7%",
    other: "33.7%",
  },
  {
    id: 2,
    thumbnail: "/assets/img/Thumbnail.webp",
    title: "lightsound/nexst-tailwind 1",
    content: "Next.js starter template.",
    typescript: "65.5%",
    javascript: "33.7%",
    other: "33.7%",
  },
  {
    id: 3,
    thumbnail: "/assets/img/Thumbnail.webp",
    title: "lightsound/nexst-tailwind 2",
    content: "Next.js starter template.",
    typescript: "65.5%",
    javascript: "33.7%",
    other: "33.7%",
  },
  {
    id: 4,
    thumbnail: "/assets/img/Thumbnail.webp",
    title: "lightsound/nexst-tailwind 2",
    content: "Next.js starter template.",
    typescript: "65.5%",
    javascript: "33.7%",
    other: "33.7%",
  },
  {
    id: 5,
    thumbnail: "/assets/img/Thumbnail.webp",
    title: "lightsound/nexst-tailwind 2",
    content: "Next.js starter template.",
    typescript: "65.5%",
    javascript: "33.7%",
    other: "33.7%",
  },
  {
    id: 6,
    thumbnail: "/assets/img/Thumbnail.webp",
    title: "lightsound/nexst-tailwind 2",
    content: "Next.js starter template.",
    typescript: "65.5%",
    javascript: "33.7%",
    other: "33.7%",
  },
];
